### ISSUE TITLE
Very promising!!! Instructions for API

### ISSUE THREAD

**Issue by kstampo** [ndrwbdnz/polylang_google_API_translate#1]
Any updates maybe?

**Comment by ndrwbdnz** [comment]
What doesn't work? Please describe details.
Did you enter google translate API key?
I will make documentation in my free time.
I use this plugin and everything works fine.

**Comment by kstampo** [comment]
Where shall I enter the API key?
Thanks!

**Comment by ndrwbdnz** [comment]
Wordpress -> Settings -> Polylang Auto Translate

**Comment by ndrwbdnz** [comment]
here is guide how to get the API key: https://translatepress.com/docs/automatic-translation/generate-google-api-key/

**Comment by kstampo** [comment]
Thanks a million mate!!! 
You've been most helpful!

**Comment by ndrwbdnz** [comment]
I'm glad to know that it's working.
A new update and docs are coming.
Please leave a star if you like the plugin.

Take care!

**Comment by kstampo** [comment]
ofcourse!
May I ask you, if there is a possibility of automatic translation of all woocommerce products which are visible and/or published, without having to choose them one-by-one?

**Comment by ndrwbdnz** [comment]
I can add such a function next weekend.

**Comment by kstampo** [comment]
brilliant!!! 
I'll be waiting!
Thanks a million!

**Comment by kstampo** [comment]
sorry to bother you once again, but I'm getting now this error:
Fatal error: Uncaught Error: Cannot use object of type WP_Error as array in /var/www/vhosts/<...deleted by me...>/wp-content/plugins/polylang-google-api-translate-master/polylang-google-api-translate.php:770 Stack trace: #0 /var/www/vhosts/<...deleted by me...>/wp-content/plugins/polylang-google-api-translate-master/polylang-google-api-translate.php(721): PAT_translate_class->pat_translate_terms('el', 'en', Object(WP_Term), 'product_visibil...', 'copy') #1 /var/www/vhosts/<...deleted by me...>/wp-content/plugins/polylang-google-api-translate-master/polylang-google-api-translate.php(535): PAT_translate_class->pat_translate_post_taxonomies('el', 'en', Array, '79462') #2 /var/www/vhosts/<...deleted by me...>/wp-content/plugins/polylang-google-api-translate-master/polylang-google-api-translate.php(281): PAT_translate_class->pat_translate_product('79462', 'el', 'en') #3 /var/www/vhosts/<...deleted by me...>/my in /var/www/vhosts/<...deleted by me...>/wp-content/plugins/polylang-google-api-translate-master/polylang-google-api-translate.php on line 770

**Comment by kstampo** [comment]
and more...
Warning: Undefined property: stdClass::$error in /var/www/vhosts/<...deleted by me...>/<...deleted by me...>/wp-content/plugins/polylang-google-api-translate-master/polylang-google-api-translate.php on line 822

Warning: Undefined property: stdClass::$error in /var/www/vhosts/<...deleted by me...>/<...deleted by me...>/wp-content/plugins/polylang-google-api-translate-master/polylang-google-api-translate.php on line 822

Warning: Undefined property: stdClass::$error in /var/www/vhosts/<...deleted by me...>/<...deleted by me...>/wp-content/plugins/polylang-google-api-translate-master/polylang-google-api-translate.php on line 822

Warning: Undefined property: stdClass::$error in /var/www/vhosts/<...deleted by me...>/<...deleted by me...>/wp-content/plugins/polylang-google-api-translate-master/polylang-google-api-translate.php on line 822

Warning: Undefined array key 0 in /var/www/vhosts/<...deleted by me...>/<...deleted by me...>/wp-content/plugins/polylang-google-api-translate-master/polylang-google-api-translate.php on line 696

Warning: Uninitialized string offset 0 in /var/www/vhosts/<...deleted by me...>/<...deleted by me...>/wp-content/plugins/polylang-google-api-translate-master/polylang-google-api-translate.php on line 696

Warning: Uninitialized string offset 0 in /var/www/vhosts/<...deleted by me...>/<...deleted by me...>/wp-content/plugins/polylang-google-api-translate-master/polylang-google-api-translate.php on line 696

Warning: Uninitialized string offset 0 in /var/www/vhosts/<...deleted by me...>/<...deleted by me...>/wp-content/plugins/polylang-google-api-translate-master/polylang-google-api-translate.php on line 696

Warning: Uninitialized string offset 0 in /var/www/vhosts/<...deleted by me...>/<...deleted by me...>/wp-content/plugins/polylang-google-api-translate-master/polylang-google-api-translate.php on line 696

Warning: Uninitialized string offset 0 in /var/www/vhosts/<...deleted by me...>/<...deleted by me...>/wp-content/plugins/polylang-google-api-translate-master/polylang-google-api-translate.php on line 696

Warning: Uninitialized string offset 0 in /var/www/vhosts/<...deleted by me...>/<...deleted by me...>/wp-content/plugins/polylang-google-api-translate-master/polylang-google-api-translate.php on line 696

Warning: Uninitialized string offset 0 in /var/www/vhosts/<...deleted by me...>/<...deleted by me...>/wp-content/plugins/polylang-google-api-translate-master/polylang-google-api-translate.php on line 696

Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, string given in /var/www/vhosts/<...deleted by me...>/<...deleted by me...>/wp-content/plugins/polylang-google-api-translate-master/polylang-google-api-translate.php:793 Stack trace: #0 /var/www/vhosts/<...deleted by me...>/<...deleted by me...>/wp-content/plugins/polylang-google-api-translate-master/polylang-google-api-translate.php(746): PAT_translate_class->pat_translate_text() #1 /var/www/vhosts/<...deleted by me...>/<...deleted by me...>/wp-content/plugins/polylang-google-api-translate-master/polylang-google-api-translate.php(721): PAT_translate_class->pat_translate_terms() #2 /var/www/vhosts/<...deleted by me...>/<...deleted by me...>/wp-content/plugins/polylang-google-api-translate-master/polylang-google-api-translate.php(535): PAT_translate_class->pat_translate_post_taxonomies() #3 /var/www/vhosts/<...deleted by me...>/<...deleted by me...>/wp-content/plugins/polylang-google-api-translate-master/polylang-google-api-translate.php(281): PAT_translate_class->pat_translate_product() #4 /var/www/vhosts/<...deleted by me...>/<...deleted by me...>/wp-includes/class-wp-hook.php(303): PAT_translate_class->pat_auto_translate_handler() #5 /var/www/vhosts/<...deleted by me...>/<...deleted by me...>/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters() #6 /var/www/vhosts/<...deleted by me...>/<...deleted by me...>/wp-includes/plugin.php(470): WP_Hook->do_action() #7 /var/www/vhosts/<...deleted by me...>/<...deleted by me...>/wp-admin/admin-post.php(70): do_action() #8 {main} thrown in /var/www/vhosts/<...deleted by me...>/<...deleted by me...>/wp-content/plugins/polylang-google-api-translate-master/polylang-google-api-translate.php on line 793

**Comment by ndrwbdnz** [comment]
For the first issue it looks like there is a problem with translating term "product_visibility" term of product id 79462.
I will see what could be the reason later.

**Comment by kstampo** [comment]
Looks like the problem occurs:
1. when product is featured (asterisk in the product list).
2. when product_tags translation is attempted. If it is excluded from translation, everything runs smoothly

Hope it helps! Waiting for some upgrade, if you plan to!

**Comment by ndrwbdnz** [comment]
So after some investigation:
The "featured" star is a specific type of taxonomy (product_visibility) that does not get translated and is only available in "one language". Polylang does not attempt to translate it - it is used in "one version" for all language versions.
I have not used the featured star on my website, so I haven't run into this problem before.
I have added a way to handle this type of taxonomies.

Regarding product tags - it might be a problem connected to the one with featured product issue. If you have product tags that have the same name and slug, woocommerce might consider the translated version to be the same as the original version and throw this error. Unfortunately I cannot replicate this issue on my side.

The plugin now tries to handle that issue (the same way as in case of a featured product tag), but I cannot guarantee that the results will be as expected. Please check the plugin and let me know.

**Comment by kstampo** [comment]
Brilliant!!!!! Thank you!
Works like a charm!
1. Featured items is not a problem anymore.
2. More importantly, product tags are translated as wel!!

You've made a great job really! Congrats!
One last thing though; Can you make it possible to proceed to BULK product translations, instead of one by one? Possibly, using some product features, i.e. translate only visible products or published products.

Thank you once again for your wonderful job. Keep on!

**Comment by ndrwbdnz** [comment]
Thank you.
Regarding bulk translation - I want to do it as bulk actions, so only selected products would be translated to all the missing languages for each product.
This however requires ajaxifying the whole process to prevent server timeouts (if the user selects hunderds of products, each with a few languages), as well as treating each translation separately, so that errors can be handled interactively.
For now I suggest that you click each auto-translation icon while holding CTRL down. This way the link will be opened in a new browser tab and you can have about a dozen simultaneous translations running - each in a new tab.
Cheers

**Comment by ndrwbdnz** [comment]
Hi. I have added bulk translation functions. Please see documentation and if they work correctly. Your feedback will be appreciated.
Cheers

**Comment by kstampo** [comment]
Thank you very much for your notification.
Before procceding:
1. I've managed to translate all my products through a very simple python script I wrote using your script. It has a lot of flaws but it does the job!
2. I'm translating only products (together with categories and terms), no posts or anything else

So far, with your previous version the only problem I had  is that some of the product terms are getting translated, while others on. I can;t figure out a pattern. Worth to mention though, that originally my terms were NOT translated.
Product categories on the other hand, are translated perfectly. Maybe this has to do with the gact that i had translated categories (by hand) before trying the product translation (as I've told you this is not the case with terms).

For the new -auto trasnlate- version now.
1.  In the menu there are 3 options: a. Re-link trasnlations (haven't tried yet), b. Auto-trasnlate selected c. Translate.
2. If I choose a couple of untrasnlated products and select b.Auto-translate, I get the message: _Bulk translation can only be done via Ajax. Please check that your browser does not block javascript and that there are no errors in the javascript console._ For sure, my browser doesn't block javascript and I see no errors in javascript console.
3. If i choose c.Translate the I get a mini menu: one to select the desired languge (ok), and the other Action. No matter what I choose in Action products look like they are trasnlated (new product with the desired flag appear) but no translation occurs (all text remains in the original language).
4. And another remark; when I use your button for translating one product, no small windows appears as it is written in the instructions, but translation is ok.

Hope, I'm in help!
Glad to test again!
Kostas

**Comment by ndrwbdnz** [comment]
Thank you for the feedback.
Reg. 2 & 4: It seems that the plugin javascript file was cached - please clear the browser cache so that the file can be loaded. Please try pressing Ctrl+R or looking into your network panel in dev tools, finding there pat.js file, right-clicking it and selecting "clear cache" or something along those lines.
Reg. 1 & 3: The "Translate" bulk action is a standard Polylang function.
Regarding why some terms are not translated - I would have to see what terms there are and how they are linked with products etc.
In my case:
1. I had a clean one-language version website,
2. then I added polylang languages only completing polylang setup wizard, so I have not done _any_ manual post, products, categories or tags translations.
3. then I translated products, posts and pages using auto-translate functions - all categories and tags were translated and linked correctly.

Please remember - tags and categories are linked both to posts (and products, etc) - this is normal wordpress linking.
The language versions of categories and tags, attribute values, etc are also linked to each other - just like language versions of posts, pages and products - this is polylang linking.
If you select post (page, product) auto translation, the plugin takes a post (or page, product, etc) and checks what categories and tags this post has. Then it checks if there already are different language versions of this tag (linked by polylang! If they are not linked by polylang, the plugin will not recognize them). It the plugin finds such a linked verion, then it assumes that the translation was already done and assigns this linked version to the translated post. If it does not find a linked language version of the category or tag, then it translated the category, creates a new category in the new language and links it to the original category, and assigns it to the new post.

Alternatively to translating posts (pages, products), you can first try to translate all categories and tags. They will be simply translated and linked. You will have more control over how they get translated. Once you finish with those taxonomies translation, you can proceed with post (page, product) translation, and the plugin will find the linked translations of taxonomies, because they would have been created in the previous step.

The re-linking tool in bulk actions is to help clean up any mess with polylang linking that may happen. Polylang itself enables editing the links, but to do this, you have to enter each category or other taxonomy, post, product, etc in edit mode and one-by-one edit the linked entries. The bulk re-link tool enables you to do it from the table-list view.

**Comment by kstampo** [comment]
Reg. 2 & 4: Clearing the cache did the trick! Great!
I will follow your suggestion for terms and categories, and I will notify you accordingly!
Thanks!
